Add regression tests to cover issue #1
    --- FAIL: TestSlug (0.00s)
        shard_test.go:21: Slug(http://www.reddit.com.): error: www.reddit.com. is a suffix
        shard_test.go:21: Slug(www.reddit.com/.): error: www.reddit.com/. is a suffix
        shard_test.go:21: Slug(www.reddit.com.): error: www.reddit.com. is a suffix
    --- FAIL: TestShardId (0.00s)
        shard_test.go:32: ShardId(http://www.reddit.com., 8): error: www.reddit.com. is a suffix
        shard_test.go:32: ShardId(www.reddit.com/., 8): error: www.reddit.com/. is a suffix
        shard_test.go:32: ShardId(www.reddit.com., 8): error: www.reddit.com. is a suffix
    FAIL
    FAIL	_/Users/ww/Local/giashard	0.100s
    FAIL